### ISSUE TITLE
Add error handling to Rust trade logic

### ISSUE THREAD

**Issue by dpaiton** [delvtech/hyperdrive-rs#33]
## Tasks:

- synchronize trade functions (openLong, openShort, add liquidity, etc) erros btwn rs & sol
  - [ ] openLong
    - [x] requested trade too small
    - [ ] requested trade too big
    - [ ] differential testing
  - [ ] openShort
    - [x] requested trade too small
    - [ ] requested trade too big
    - [ ] differential testing
  - [ ] closeLong
    - [x] requested trade too small
    - [ ] requested trade too big
    - [ ] differential testing
  - [ ] closeShort
    - [x] requested trade too small
    - [ ] requested trade too big
    - [ ] differential testing
  
Another issue (https://github.com/delvtech/hyperdrive/issues/871) will address these:
- [ ] make getMaxLong rs safer by returning 0 when market is in edge case
- [ ] make getMaxShort rs safer by returning 0 when market is in edge case

When these functions are added (https://github.com/delvtech/hyperdrive/issues/873 https://github.com/delvtech/hyperdrive-rs/issues/24 https://github.com/delvtech/hyperdrive-rs/issues/22) we should ensure they also have matching errors:
  - [ ] addLiquidity
  - [ ] removeLiquidity
  - [ ] redeemWithdrawShares

## Details:
The Solidity code includes error handling which the Rust SDK lacks. For instance, in Solidity, openLong reverts with a NegativeInterest error, while in Rust it incorrectly returns a valid FixedPoint number. This discrepancy can lead to issues where users might pay gas for transactions that are destined to fail. It also can introduce bugs in Python bot logic that relies on these outputs for choosing subsequent trades.

Here is a python script to reproduce the given example:

```py
"""Demonstrate failure of rust module to produce the same errors as the solidity contracts."""
from fixedpointmath import FixedPoint
from agent0.hyperdrive.interactive import LocalChain
from agent0.interactive_fuzz.helpers import setup_fuzz


if __name__ == "__main__":
    # Setup the environment
    chain_config = LocalChain.Config
    log_to_stdout = False
    log_filename = ".logging/check_rust_error.log"
    chain, random_seed, rng, interactive_hyperdrive = setup_fuzz(
        log_filename,
        chain_config,
        log_to_stdout,
        fuzz_test_name="check_rust_error",
        flat_fee=FixedPoint(0),
        curve_fee=FixedPoint(0.001),  # 0.1%
        governance_lp_fee=FixedPoint(0),
        governance_zombie_fee=FixedPoint(0),
        var_interest=FixedPoint(0.0),
    )

    current_pool_state = interactive_hyperdrive.hyperdrive_interface.current_pool_state
    max_long = interactive_hyperdrive.hyperdrive_interface.calc_max_long(FixedPoint(1e15), current_pool_state)
    trade_amount = max_long + FixedPoint(100)  # trade more than the max
    long_agent = interactive_hyperdrive.init_agent(base=FixedPoint(1e15), eth=FixedPoint(1e3), name="joe")

    # rust version
    bonds_purchased_rust = interactive_hyperdrive.hyperdrive_interface.calc_open_long(trade_amount, current_pool_state)
    # Rust code succeeds:
    # bonds_purchased_rust = FixedPoint("99793307.650604214737873666")

    # smart contract version
    open_long_event = long_agent.open_long(trade_amount)
    # Contract throws an error: web3.exceptions.ContractCustomError: ('0x512095c7', 'ContractCustomError NegativeInterest raised.')

    # Cant assign this because it fails
    # bonds_purchased_sol = open_long_event.bond_amount
    
    # TODO: assert solidity error == rust error
```
